<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Actio.Core\Actio.Core.csproj" />
    <ProjectReference Include="..\Actio.Engine\Actio.Engine.csproj" />
    <ProjectReference Include="..\Actio.Runner.Docker\Actio.Runner.Docker.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>actio</AssemblyName>
    <Version>0.1.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
