<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Actio.Core\Actio.Core.csproj" />
    <ProjectReference Include="..\Actio.Engine\Actio.Engine.csproj" />
    <ProjectReference Include="..\Actio.Runner.Docker\Actio.Runner.Docker.csproj" />
    <ProjectReference Include="..\Actio.Storage\Actio.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
